### ISSUE TITLE
Application fails to Start in Linux Mint 18

### ISSUE THREAD

**Issue by balogic** [BoostIO/Boostnote#1316]
```
module.js:472
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/usr/share/boostnote/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/usr/share/boostnote/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/usr/share/boostnote/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:300:26)
```
Can't Start Boostnote after Fresh Install

**Comment by mslourens** [comment]
I've got a couple of clarifying questions:

- Which particular version of LinuxMint 18 did you try to install Boostnote? The latest, 18.2? 
- Which windowmanager do you use (Cinnamon, Xfce, Mate or KDE)? 
- How did you install Boostnote?

**Comment by balogic** [comment]
@mslourens 
* Linux Mint 18.3
* Cinnamon
* Through `.deb` package downloaded from the official website

**Comment by mslourens** [comment]
I just installed that version in a VM and downloaded and installed Boostnote. It started without any issues.

**Comment by balogic** [comment]
It worked :tada: :tada: :tada:
I just deleted the `Boostnote` folder inside `~/.config` and reinstalled it again.
