### ISSUE TITLE
Cannot find module 'lodash' on RPM

### ISSUE THREAD

**Issue by comzeradd** [BoostIO/Boostnote#1441]
I followed the instructions from Readme to build an rpm for Boostnote. Everything went fine, but when I run it I get an error for lodash and the app never starts.

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/usr/share/boostnote/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/boostnote/resources/app/lib/main-app.js:7:11)
    at Object.<anonymous> (/usr/share/boostnote/resources/app/lib/main-app.js:130:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by threkk** [comment]
Have you tried running `npm install lodash` instead of `rpm`? `lodash` is a node package.

**Comment by comzeradd** [comment]
But shouldn't that be part of the `grunt build` step? Otherwise what's the point of building an rpm and installing it?

**Comment by Flexo013** [comment]
@comzeradd Is this still an issue that requires investigation of the Boostnote team or is this issue no longer relevant?

**Comment by comzeradd** [comment]
I don't use a rpm-based desktop distro at the moment, so I can't confirm if the error persists.

**Comment by Flexo013** [comment]
Then I will close this for now. If future problems occur with RPM then we will just create a new issue.
