### ISSUE TITLE
No storage mount...

### ISSUE THREAD

**Issue by vikin** [BoostIO/Boostnote#1466]
app-0.8.20\resources\app\node_modules\mkdirp\index.js:90 Uncaught RangeError: Maximum call stack size exceeded
    at String.slice (native)
    at Object.resolve (path.js:260:27)
    at Object._makeLong (path.js:664:32)
    at fs.mkdirSync (fs.js:895:35)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:669:16)
    at sync (F:\boost1\app-0.8.20\resources\app\node_modules\mkdirp\index.js:71:13)
    at sync (F:\boost1\app-0.8.20\resources\app\node_modules\mkdirp\index.js:77:24)
    at sync (F:\boost1\app-0.8.20\resources\app\node_modules\mkdirp\index.js:77:24)
    at sync (F:\boost1\app-0.8.20\resources\app\node_modules\mkdirp\index.js:77:24)
    at sync (F:\boost1\app-0.8.20\resources\app\node_modules\mkdirp\index.js:77:24)

**Comment by kazup01** [comment]
I can not understand your state. Could you tell me in more detail?

**Comment by Flexo013** [comment]
Closing due to no response from issue reporter.
