### ISSUE TITLE
Systray icon gives error when window closed using X

### ISSUE THREAD

**Issue by jerry1970** [BoostIO/Boostnote#1487]
Ubuntu 17.04 with XFCE, Boostnote 0.8.20

When the main window is closed (using Alt-F4 or the X button in the window's title bar), the systray icon remains visible. When I right-click that icon and select **Open Main Window**, I get the following error:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Object has been destroyed
    at Server.toggleMainWindow (/usr/share/boostnote/resources/app/lib/ipcServer.js:20:22)
    at Server.emit (/usr/share/boostnote/resources/app/node_modules/event-pubsub/es6.js:64:21)
    at Server.gotData (/usr/share/boostnote/resources/app/node_modules/node-ipc/dao/socketServer.js:186:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

When I start Boostnote again from the menu or command line, I get this error:
```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Object has been destroyed
    at Function.<anonymous> (/usr/share/boostnote/resources/app/lib/main-app.js:20:16)
```

I have to select **Quit** from the systray menu before I can start Boostnote again.

I have a keyboard shortcut for Boostnote, I don't need the systray icon. May I suggest a setting so I can switch off the use of the systray icon?

**Comment by kazup01** [comment]
Hi @jerry1970 , sorry for the inconvenience. Please check it. #1396
