### ISSUE TITLE
LINUX DEB 64BIT package is wrong

### ISSUE THREAD

**Issue by vmaks** [BoostIO/Boostnote#1604]
Something wrong with current *boostnote_0.10.0_amd64* package.
I can't install it on Ubuntu 14.04 x64.

An error message is following: 
```The package is of bad quality```

Details:
```
Lintian check results for /home/USER_NAME/Downloads/boostnote_0.10.0_amd64.deb:
no entry control.tar.gz in archive

gzip: stdin: unexpected end of file
/bin/tar: Child returned status 1
/bin/tar: Error is not recoverable: exiting now
```

Could you fix it?

Thanks in advance!

**Comment by charrismatic** [comment]
The program crashed at launch of me as well

with the following error 


```
module.js:472
    throw err;
    ^
Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/usr/share/boostnote/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/usr/share/boostnote/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/usr/share/boostnote/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)
```

Running Ubuntu 17.10 4.14.21-041421-generic x86_64 x86_64 x86_64 GNU/Linux

**Comment by Rokt33r** [comment]
This sounds critical. I'll fix it asap.

**Comment by Rokt33r** [comment]
Fixed. Please download again. https://github.com/BoostIO/boost-releases/releases/download/v0.10.0/boostnote_0.10.0_amd64.deb
