### ISSUE TITLE
Version 0.11.3 won't start on Windows

### ISSUE THREAD

**Issue by Oylex** [BoostIO/Boostnote#1762]
(I can't take any screenshot, because the app never shows up.)

So when I launch the app, I see in the Task Manager that it starts and closes immediately.

I found a workaround, in the Boostnote install directory `C:\Users\Joel\AppData\Local\boost`, there is also a directory for the previous version (0.11.2), this one works, but you have to launch it directly from that exe or a shortcut to it, it won't work if you pin it to the taskbar.

This is the squirrel log of the first launch:

```
2018-03-28 11:13:58> Program: Starting Squirrel Updater: --createShortcut Boostnote.exe
2018-03-28 11:13:58> ApplyReleasesImpl: About to create shortcuts for Boostnote.exe, rootAppDir C:\Users\Joel\AppData\Local\boost
2018-03-28 11:13:58> ApplyReleasesImpl: Creating shortcut for Boostnote.exe => C:\Users\Joel\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\MAISIN&CO., Inc.\Boostnote.lnk
2018-03-28 11:13:59> ApplyReleasesImpl: About to save shortcut: C:\Users\Joel\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\MAISIN&CO., Inc.\Boostnote.lnk (target C:\Users\Joel\AppData\Local\boost\Boostnote.exe, workingDir C:\Users\Joel\AppData\Local\boost\app-0.11.2, args , toastActivatorCSLID 2478f3fa-2422-5e13-b668-0a2a64a8cf2d)
2018-03-28 11:13:59> ApplyReleasesImpl: Creating shortcut for Boostnote.exe => C:\Users\Joel\Desktop\Boostnote.lnk
2018-03-28 11:13:59> ApplyReleasesImpl: About to save shortcut: C:\Users\Joel\Desktop\Boostnote.lnk (target C:\Users\Joel\AppData\Local\boost\Boostnote.exe, workingDir C:\Users\Joel\AppData\Local\boost\app-0.11.2, args , toastActivatorCSLID 2478f3fa-2422-5e13-b668-0a2a64a8cf2d)
2018-03-28 11:13:59> ApplyReleasesImpl: Examining Pin: Adobe Illustrator CC 2015.lnk
2018-03-28 11:13:59> ApplyReleasesImpl: Examining Pin: Adobe Photoshop CC 2015.lnk
2018-03-28 11:13:59> ApplyReleasesImpl: Examining Pin: Android Studio.lnk
2018-03-28 11:13:59> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2018-03-28 11:13:59> ApplyReleasesImpl: Examining Pin: Chrome.lnk
2018-03-28 11:13:59> ApplyReleasesImpl: Examining Pin: notepad++.lnk
2018-03-28 11:13:59> ApplyReleasesImpl: Examining Pin: PhpStorm.lnk
2018-03-28 11:13:59> ApplyReleasesImpl: Examining Pin: Sourcetree.lnk
2018-03-28 11:13:59> ApplyReleasesImpl: Examining Pin: Visual Studio 2017.lnk
2018-03-28 11:13:59> ApplyReleasesImpl: Examining Pin: Windows PowerShell.lnk
2018-03-28 11:14:11> Program: Starting Squirrel Updater: --checkForUpdate https://github.com/BoostIO/boost-releases/releases/download/v0.11.3
2018-03-28 11:14:11> Program: Fetching update information, downloading from https://github.com/BoostIO/boost-releases/releases/download/v0.11.3
2018-03-28 11:14:11> CheckForUpdateImpl: Generated new staging user ID: 60c573a3-a8cf-5a9e-8e13-f32c1b47638a
2018-03-28 11:14:11> CheckForUpdateImpl: Downloading RELEASES file from https://github.com/BoostIO/boost-releases/releases/download/v0.11.3
2018-03-28 11:14:11> FileDownloader: Downloading url: https://github.com/BoostIO/boost-releases/releases/download/v0.11.3/RELEASES?id=boost&localVersion=0.11.2&arch=amd64
2018-03-28 11:14:12> UpdateInfo: Couldn't get release notes for:boost-0.11.3-full.nupkg: System.IO.FileNotFoundException: Could not find file 'C:\Users\Joel\AppData\Local\boost\packages\boost-0.11.3-full.nupkg'.
File name: 'C:\Users\Joel\AppData\Local\boost\packages\boost-0.11.3-full.nupkg'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.ZipPackage.<>c__DisplayClass9_0.<.ctor>b__0()
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
```

**Comment by Rokt33r** [comment]
It seems some processes of boostnote still alive. Could you try it again after restarting your pc?

**Comment by aaronh86** [comment]
I have the same problem. After update, I received a VCRUNTIME140.dll missing error. Then, after installing the C++ runtime library it asked, I get no error, but it doesn't open.

**Comment by Oylex** [comment]
if it helps, I wasn't prompted for that dll, but I have visual studio
installed

**Comment by Rokt33r** [comment]
Could you discard everything in `C:\Users\Joel\AppData\Local\boost` and reinstall the app again?

Btw, I'd very rarely experienced the problem with bad internet connection.

**Comment by Oylex** [comment]
@Rokt33r Still doesn't work. Are there logs somewhere beside the updater's log?

**Comment by i-give-up** [comment]
Same problem here. Win 8.1 64-bit. 

I was mucking around with procmon and noticed that 0.11.3 is missing the `electron.asar` file, i.e. it's not in the `%localappdata%/boost/app-0.11.3/resources` directory.

I renamed the `electron.asar` for the older version 0.11.2 just to see what happens and it also causes 0.11.2 not starting. That version starts fine otherwise.

So I'm guessing the missing `electron.asar` have something to do with 0.11.3 not starting.

**Comment by Oylex** [comment]
It's working again for me with 0.11.4

Good Job!

**Comment by PureCS** [comment]
Having this issue on 0.11.5 (windows 10 x64), however 0.11.4 works fine.

**Comment by w33zy** [comment]
Having this issue on 0.11.5 (Windows 10 x64)

**Comment by FunkMonkey** [comment]
Having this issue on 0.11.6 and 0.11.7 (Windows 10 x64). 
0.11.5 works fine!
