### ISSUE TITLE
can not add storage

### ISSUE THREAD

**Issue by TangSirOnGit** [BoostIO/Boostnote#1871]
# Current behavior
After I reboot my mac this morning, the bootsNote did not load the local notes.
 Then I open the preferences page, the storage is empty, and I can not add storage.
the  `add` button on this page is invalid.

<img width="1280" alt="2018-04-26 12 36 22" src="https://user-images.githubusercontent.com/10524715/39286075-7f2d7afc-494e-11e8-9546-1011697d04b2.png"> 

# Expected behavior
Display the notes I've added .
# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version : 0.11.4
- OS Version and name : mac OS 10.1.3.4

**Comment by TangSirOnGit** [comment]
# Environment

- Version : 0.11.4
- OS Version and name : mac OS 10.1.3.4

**Comment by rayou** [comment]
Hi @TangSirOnGit 

Did your dropbox folder mount successfully?

**Comment by jeffreyzupka** [comment]
Hello. I am also seeing the same issue after updating to version 0.11.4. I am trying to add an existing Dropbox storage location. My environment

* Version: 0.11.4
* OS: macOS 10.13.2

**Comment by rdx565** [comment]
Hi. I'm seeing the same issue after updating to version 0.11.5. 

Dropbox is available and syncing. I can open the files in boostnote-mobile in other apps, but I can't add it to the Boostnote Mac app as storage and any folder that is added vanishes on restarting. This includes local folders which are not synced in any way.

My environment:
Version 0.11.5 
OS: macOS 10.13.4

**Comment by rayou** [comment]
Hi @rdx565 

Could you open developer tools (View -> Toggle Developer Tools) then switch to console tab, add the folder again, if you see any error logs, please paste it here.

Thanks

**Comment by rdx565** [comment]
`main.js:4005 Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined
    at file:///Applications/Boostnote.app/Contents/Resources/app/compiled/main.js:4005:19
    at Array.forEach (native)
    at data (file:///Applications/Boostnote.app/Contents/Resources/app/compiled/main.js:3982:21)
    at file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/redux/dist/redux.min.js:1:5926
    at s (file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/redux/dist/redux.min.js:1:1820)
    at file:///Applications/Boostnote.app/Contents/Resources/app/compiled/main.js:62962:10
    at <anonymous>:null:null

(anonymous) @ main.js:4005
data @ main.js:3982
(anonymous) @ redux.min.js:1
s @ redux.min.js:1
(anonymous) @ main.js:62962`

**Comment by VizualAbstract** [comment]
I'm also experiencing this problem. All of my notes for several important meetings coming up are stored here, now I have no access to them.

**Comment by VizualAbstract** [comment]
In desperate need of those notes, so I just went into `Boostnote.app/Contents/Resources/app/compiled/main.js` and on line `3595`, I added `if (!note.tags) { return; }`

**Comment by VizualAbstract** [comment]
I had to add it in several other locations as well, mostly anywhere `note.tags` is being used.

**Comment by rdx565** [comment]
This solution works, but has to be redone whenever the app updates, is an official solution possible?

**Comment by ismaeIfm** [comment]
I had the same issue, but I noticed that if I deleted some of the notes I could add the storage, so I thought that there was a problem in some of the notes. I checked all of them and I found that one note had these contents:
```'content': ''```
So I just deleted and everything works fine. Hope this helps.

**Comment by Flexo013** [comment]
If this issue occurs again, then comment here and we will reopen this issue.

**Comment by ismaeIfm** [comment]
For me happens every once in a while. And I also use Dropbox sync.

**Comment by Flexo013** [comment]
@ismaeIfm When this occurs is it happening to a specific note? Is it large, small, or just random? Do you recover the contents of the lost note using Dropbox? Any other things that you have noticed that might help in pinning down the cause of this issue?

**Comment by mdeuerlein** [comment]
Same here with a dropbox synced storage. Boostnote lost the storage and it cannot be re-added so it's not possible access my notes and content. Moving the content from the dropbox folder to a local folder outside the dropbox doesn't fix the problem.

### Error Message in Developer Tools when trying to re-add the storage:

<img width="1754" alt="Screenshot" src="https://user-images.githubusercontent.com/14030524/71646031-28ae5980-2ce1-11ea-8524-4b47df39ec32.png">

```
Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined
    at assignToTags (file:///private/var/folders/fy/89kjv9gs5sxdn9b21p6ts0mc0000gn/T/AppTranslocation/02C32412-1718-4720-8774-BEC44B6BC5D6/d/Boostnote.app/Contents/Resources/app/compiled/main.js:5141:9)
    at file:///private/var/folders/fy/89kjv9gs5sxdn9b21p6ts0mc0000gn/T/AppTranslocation/02C32412-1718-4720-8774-BEC44B6BC5D6/d/Boostnote.app/Contents/Resources/app/compiled/main.js:4741:10
    at Array.some (<anonymous>:null:null)
    at data (file:///private/var/folders/fy/89kjv9gs5sxdn9b21p6ts0mc0000gn/T/AppTranslocation/02C32412-1718-4720-8774-BEC44B6BC5D6/d/Boostnote.app/Contents/Resources/app/compiled/main.js:4722:21)
    at file:///private/var/folders/fy/89kjv9gs5sxdn9b21p6ts0mc0000gn/T/AppTranslocation/02C32412-1718-4720-8774-BEC44B6BC5D6/d/Boostnote.app/Contents/Resources/app/node_modules/redux/dist/redux.min.js:1:4863
    at a (file:///private/var/folders/fy/89kjv9gs5sxdn9b21p6ts0mc0000gn/T/AppTranslocation/02C32412-1718-4720-8774-BEC44B6BC5D6/d/Boostnote.app/Contents/Resources/app/node_modules/redux/dist/redux.min.js:1:1193)
    at file:///private/var/folders/fy/89kjv9gs5sxdn9b21p6ts0mc0000gn/T/AppTranslocation/02C32412-1718-4720-8774-BEC44B6BC5D6/d/Boostnote.app/Contents/Resources/app/compiled/main.js:68302:10
```



Boostnote Version 0.11.15 
MacOS Catalina 10.15.2

**Comment by mdeuerlein** [comment]
> For me happens every once in a while. And every time it happens I just need to delete the note that has `'content': ''` and everything works again. I also use Dropbox sync.
fixed my problem. thanks @ismaeIfm

**Comment by ismaeIfm** [comment]
> @ismaeIfm When this occurs is it happening to a specific note? Is it large, small, or just random? Do you recover the contents of the lost note using Dropbox? Any other things that you have noticed that might help in pinning down the cause of this issue?

@Flexo013 it seems to be a new random note every time.

**Comment by Flexo013** [comment]
@ismaeIfm Hmmm, that will make it hard to find out what's causing this. Currently my best guess if some quirk in combination with how Dropbox updates/syncs files.

**Comment by ismaeIfm** [comment]
@Flexo013 I have noticed when it happens and the thing is that this random note with content `'content': ''` appears every time I access my notes with the iOS app https://github.com/BoostIO/boostnote-mobile/issues/201

**Comment by Flexo013** [comment]
@ismaeIfm The iOS app is no longer supported. So any bugs caused by it will not be fixed.

There are no plans for a mobile app for Boostnote. Boost Note.next does have a mobile version planned.
