### ISSUE TITLE
Right Clicking does not reveal context menu

### ISSUE THREAD

**Issue by looselytyped** [BoostIO/Boostnote#2206]
# Current behavior

## Right-Click on Notes List

<img width="2133" alt="image" src="https://user-images.githubusercontent.com/20939/42733835-cb18a6d4-8806-11e8-8383-87ffe6602cb0.png">

## Right Click on Preview 

<img width="2133" alt="image" src="https://user-images.githubusercontent.com/20939/42733847-377a4d78-8807-11e8-8b76-5a413084cd2f.png">

# Expected behavior

Expect to see a context menu

# Steps to reproduce

1. Open Boostnote
2. Right Click *anywhere* in the application 
3. Reveals **no** context menu

# Environment

- Version : `0.11.7`
- OS Version and name : OSX Sierra (10.12.6)

# Stacktrace

## Upon Right clicking on the Note list I see this stacktrace

```
react-dom.min.js:12 Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Options must be an object
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Options must be an object
    at callFunction (/Applications/Boostnote.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Applications/Boostnote.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Applications/Boostnote.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at callFunction (/Applications/Boostnote.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Applications/Boostnote.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Applications/Boostnote.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (/Applications/Boostnote.app/Contents/Resources/electron.asar/renderer/api/remote.js:209:30)
    at metaToValue (/Applications/Boostnote.app/Contents/Resources/electron.asar/renderer/api/remote.js:213:28)
    at Object.remoteMemberFunction (/Applications/Boostnote.app/Contents/Resources/electron.asar/renderer/api/remote.js:113:16)
    at WrappedComponent.handleNoteContextMenu (file:///Applications/Boostnote.app/Contents/Resources/app/compiled/main.js:51729:13)
    at onContextMenu (file:///Applications/Boostnote.app/Contents/Resources/app/compiled/main.js:46845:17)
    at Object.r (file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/react-dom/dist/react-dom.min.js:12:5860)
    at i (file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/react-dom/dist/react-dom.min.js:10:22344)
    at Object.s [as executeDispatchesInOrder] (file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/react-dom/dist/react-dom.min.js:10:22559)
    at f (file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/react-dom/dist/react-dom.min.js:10:18941)
    at m (file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/react-dom/dist/react-dom.min.js:10:19067)
    at Array.forEach (<anonymous>:null:null)
    at r (file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/react-dom/dist/react-dom.min.js:13:12490)
    at Object.processEventQueue (file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/react-dom/dist/react-dom.min.js:10:20125)
    at r (file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/react-dom/dist/react-dom.min.js:12:6109)
    at Object.handleTopLevel [as _handleTopLevel] (file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/react-dom/dist/react-dom.min.js:12:6179)
    at a (file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/react-dom/dist/react-dom.min.js:12:6645)
    at r.perform (file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/react-dom/dist/react-dom.min.js:13:9345)
    at Object.batchedUpdates (file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/react-dom/dist/react-dom.min.js:12:4379)
    at Object.a [as batchedUpdates] (file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/react-dom/dist/react-dom.min.js:12:23308)
    at dispatchEvent (file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/react-dom/dist/react-dom.min.js:12:7502)
```

## Upon Right clicking on the Preview I see this stacktrace

```
Uncaught TypeError: this.props.onContextMenu is not a function
    at MarkdownPreview.handleContextMenu (main.js:21927)
    at HTMLBodyElement.MarkdownPreview._this.contextMenuHandler (main.js:21864)
handleContextMenu @ main.js:21927
MarkdownPreview._this.contextMenuHandler @ main.js:21864
```

Please let me know if there is anything other piece of information I can provide. 
Thank you!

**Comment by ytee** [comment]
I am seeing his behavior too. On Windows 7.
Right click on the Notes list or any where no context menu is coming up.

Version: 0.11.7
OS: Windows 7

**Comment by m0rd3c4i** [comment]
Same errors as above.

Windows 10 Pro
Version 1709
OS Build 16299.547

**Comment by ZeroX-DG** [comment]
Confirm this is a bug! I'll try to it soon.

**Comment by looselytyped** [comment]
@Rokt33r Thank you!

Also, allow me to apologize — I did do a search across all open issues and somehow missed the fact that this had already been reported. I should have been more diligent.

That said, thank you for Boostnote and all your hard work.
