### ISSUE TITLE
Error: Cannot find module 'electron-gh-releases'

### ISSUE THREAD

**Issue by cdayjr** [BoostIO/Boostnote#2211]
# Current behavior

When I launch boostnote compiled from the instructions in [docs/build.md](https://github.com/BoostIO/Boostnote/blob/master/docs/build.md), I get the following error:

```
$ ./Boostnote
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-gh-releases'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/cdayjr/Downloads/Boostnote-0.11.7/dist/Boostnote-linux-x64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/cdayjr/Downloads/Boostnote-0.11.7/dist/Boostnote-linux-x64/resources/app/lib/main-app.js:5:20)
    at Object.<anonymous> (/home/cdayjr/Downloads/Boostnote-0.11.7/dist/Boostnote-linux-x64/resources/app/lib/main-app.js:116:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
```

This happens both with the built `rpm` package and with running `Boostnote` in the `dist/Boostnote-linux-x64` folder. I gave it a shot with both 0.11.6 and 0.11.7.

# Expected behavior

It should launch Boostnote without any issues.

# Steps to reproduce

1. Download and extract the source code.
2. Run `yarn`, `yarn run dev-start` and check it works, close it and then run, `grunt pre-build`, `sudo dnf install -y dpkg dpkg-dev rpm-build fakeroot` and finally `grunt build`
3. Install the generated `rpm` package in `dist` and launch Boostnote.

# Environment

- Version : 0.11.7 and 0.11.6
- OS Version and name : Fedora 28

**Comment by saaguero** [comment]
What version of node/npm are you using? Just double checking since that documentation says:

`You should use npm v4.x because $ grunt pre-build fails on v5.x.`

I'm personally using node v7.10.1 / npm 4.2.0 under Fedora 28.

However, I'm still facing the issue from #2204 , which I'm working around simply by copying over the missing depency `markdown-it-admonition` into `dist/Boostnote-linux-x64/resources/app/node_modules`

**Comment by cdayjr** [comment]
Nice catch. That seems to be the cause of my problem. I ran `npm install -g npm@4` and was able to get it to work after re-running the build commands. Thanks!
