### ISSUE TITLE
ever2boost crashes during import

### ISSUE THREAD

**Issue by ShakataGaNai** [BoostIO/Boostnote#2246]
# Current behavior
Running ever2boost to migrate my fairly large evernote collection to boostnote.

```
ever2boost import
DEVELOPER_TOKEN: XXXXXXXredactedXXXXXXXX
/var/lib/gems/2.5.0/gems/evernote-thrift-1.25.2/lib/thrift/protocol/base_protocol.rb:254: warning: constant ::Fixnum is deprecated
/var/lib/gems/2.5.0/gems/evernote-thrift-1.25.2/lib/thrift/protocol/base_protocol.rb:294: warning: constant ::Fixnum is deprecated
processing...
importing House
importing Education
importing Company1
Traceback (most recent call last):
	11: from /usr/local/bin/ever2boost:23:in `<main>'
	10: from /usr/local/bin/ever2boost:23:in `load'
	 9: from /var/lib/gems/2.5.0/gems/ever2boost-0.1.5/exe/ever2boost:4:in `<top (required)>'
	 8: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	 7: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	 6: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	 5: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	 4: from /var/lib/gems/2.5.0/gems/ever2boost-0.1.5/lib/ever2boost/cli.rb:16:in `import'
	 3: from /var/lib/gems/2.5.0/gems/ever2boost-0.1.5/lib/ever2boost/evernote_authorizer.rb:63:in `import'
	 2: from /var/lib/gems/2.5.0/gems/ever2boost-0.1.5/lib/ever2boost/evernote_authorizer.rb:63:in `map'
	 1: from /var/lib/gems/2.5.0/gems/ever2boost-0.1.5/lib/ever2boost/evernote_authorizer.rb:65:in `block in import'
/var/lib/gems/2.5.0/gems/ever2boost-0.1.5/lib/ever2boost/evernote_authorizer.rb:49:in `fetch_notes': undefined method `>' for nil:NilClass (NoMethodError)`
```

# Expected behavior
I'd expect it to not crash, or if it found a note it couldn't migrate - note that and move on

# Steps to reproduce

1. Run ever2boost import
2. Wait

# Environment

- Version : ever2boost-0.1.5
- OS Version and name : `Linux host 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux` -- Ubuntu 18.04

```
sudo gem install ever2boost
Fetching: evernote-thrift-1.25.2.gem (100%)
Successfully installed evernote-thrift-1.25.2
Fetching: thor-0.20.0.gem (100%)
Successfully installed thor-0.20.0
Fetching: ever2boost-0.1.5.gem (100%)
Successfully installed ever2boost-0.1.5
Parsing documentation for evernote-thrift-1.25.2
Installing ri documentation for evernote-thrift-1.25.2
Parsing documentation for thor-0.20.0
Installing ri documentation for thor-0.20.0
Parsing documentation for ever2boost-0.1.5
Installing ri documentation for ever2boost-0.1.5
Done installing documentation for evernote-thrift, thor, ever2boost after 3 seconds
3 gems installed
```

**Comment by Flexo013** [comment]
@ShakataGaNai Is this still occurring with the latest version of Boostnote?

**Comment by Flexo013** [comment]
I'm closing this issue do to prolonged inactivity.

If you still are experiencing this problem then feel free to reopen this issue or create a new issue with all the relevant information.
