### ISSUE TITLE
Uncaught Error: File reading error on Folder import

### ISSUE THREAD

**Issue by Trudko** [BoostIO/Boostnote#2500]
# Current behavior
Hi, first of all thanks for the project!

Boostnote throws an error when I try to import whole folder by drag and drop. It seems to support only files now. Unfortunately I already have folders for notes which includes subfolder and I would like to import into Boost note.

```
main.js:65189 Uncaught Error: File reading error: 
    at file:///usr/share/boostnote/resources/app/compiled/main.js:65189:27
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:495:12)

(anonymous) @ main.js:65189
readFileAfterClose @ fs.js:495
fs
VM461:1 Uncaught ReferenceError: fs is not defined
    at eval (<anonymous>:1:1)
    at file:///usr/share/boostnote/resources/app/compiled/main.js:65188:10
    at Array.forEach (<anonymous>:null:null)
    at WrappedComponent.addNotesFromFiles (file:///usr/share/boostnote/resources/app/compiled/main.js:65187:18)
    at WrappedComponent.handleDrop (file:///usr/share/boostnote/resources/app/compiled/main.js:65170:56)
    at onDrop (file:///usr/share/boostnote/resources/app/compiled/main.js:65405:28)
    at Object.r (file:///usr/share/boostnote/resources/app/node_modules/react-dom/dist/react-dom.min.js:12:5860)
    at i (file:///usr/share/boostnote/resources/app/node_modules/react-dom/dist/react-dom.min.js:10:22344)
    at Object.s [as executeDispatchesInOrder] (file:///usr/share/boostnote/resources/app/node_modules/react-dom/dist/react-dom.min.js:10:22559)
    at f (file:///usr/share/boostnote/resources/app/node_modules/react-dom/dist/react-dom.min.js:10:18941)
    at m (file:///usr/share/boostnote/resources/app/node_modules/react-dom/dist/react-dom.min.js:10:19067)
    at Array.forEach (<anonymous>:null:null)
    at r (file:///usr/share/boostnote/resources/app/node_modules/react-dom/dist/react-dom.min.js:13:12490)
    at Object.processEventQueue (file:///usr/share/boostnote/resources/app/node_modules/react-dom/dist/react-dom.min.js:10:20125)
    at r (file:///usr/share/boostnote/resources/app/node_modules/react-dom/dist/react-dom.min.js:12:6109)
    at Object.handleTopLevel [as _handleTopLevel] (file:///usr/share/boostnote/resources/app/node_modules/react-dom/dist/react-dom.min.js:12:6179)
    at a (file:///usr/share/boostnote/resources/app/node_modules/react-dom/dist/react-dom.min.js:12:6645)
    at r.perform (file:///usr/share/boostnote/resources/app/node_modules/react-dom/dist/react-dom.min.js:13:9345)
    at Object.batchedUpdates (file:///usr/share/boostnote/resources/app/node_modules/react-dom/dist/react-dom.min.js:12:4379)
    at Object.a [as batchedUpdates] (file:///usr/share/boostnote/resources/app/node_modules/react-dom/dist/react-dom.min.js:12:23308)
    at dispatchEvent (file:///usr/share/boostnote/resources/app/node_modules/react-dom/dist/react-dom.min.js:12:7502)

(anonymous) @ VM461:1
(anonymous) @ main.js:65188
addNotesFromFiles @ main.js:65187
handleDrop @ main.js:65170
onDrop @ main.js:65405
r @ react-dom.min.js:12
i @ react-dom.min.js:10
s @ react-dom.min.js:10
f @ react-dom.min.js:10
m @ react-dom.min.js:10
r @ react-dom.min.js:13
processEventQueue @ react-dom.min.js:10
r @ react-dom.min.js:12
handleTopLevel @ react-dom.min.js:12
a @ react-dom.min.js:12
perform @ react-dom.min.js:13
batchedUpdates @ react-dom.min.js:12
a @ react-dom.min.js:12
dispatchEvent @ react-dom.min.js:12
```

# Expected behavior

- Boostnote should import markdown files and create folder structure reflecting the structure of imported folder.

# Steps to reproduce
1. Create a folder
2. Add markdown file to it
3. Drag and drop folder to boostnote

# Environment

- Version :
- OS Version and name : Ubuntu 16.04

**Comment by Flexo013** [comment]
I can't reproduce this and since it's a fairly old issue I'm closing it for now. In the event that it does pop up again, feel free to comment/reopen this issue.
