### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by jangtsekiang** [BoostIO/Boostnote#2574]
I am having trouble building the project. 

Can someone help please?

```bash
yarn
yarn install v1.12.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-config-standard@6.2.1" has unmet peer dependency "eslint-plugin-promise@>=3.3.0".
[4/4] Building fresh packages...
Done in 15.16s.
```

```bash
user@machine:/media/Boostnote$ yarn run dev
yarn run v1.12.1
$ node dev-scripts/dev.js
✔  success   Webpack Dev Server listening at localhost:8080
…  watching  Waiting for webpack to bundle...
✔  success   Bundle success !
✖  error     Error: spawn EACCES 
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:503:9)
    at startElectron (/media/Boostnote/dev-scripts/dev.js:52:3)
    at startServer.then (/media/Boostnote/dev-scripts/dev.js:70:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

# Environment

node -v
v8.12.0
npm -v
6.4.1

- Version : master branch
- OS Version and name : 16.04 Ubuntu

**Comment by ZeroX-DG** [comment]
somehow the system prevents the code from starting electron. Make sure you have the right permission for the project folder. You can try to use the `sudo` command. Although I'm not sure there will be any harm if you use that command (It should not cause any problem).
```
sudo yarn run dev
```

**Comment by jangtsekiang** [comment]
@ZeroX-DG that didn't help :cry:

**Comment by ZeroX-DG** [comment]
Have you tried `sudo chown` ?

**Comment by jangtsekiang** [comment]
I had ownership so there was no need for. I cloned into $HOME/ directory and everything is fine. :1st_place_medal: 
Very wired. 

Thank you for the help, @ZeroX-DG
