### ISSUE TITLE
Boostnote 0.11.10 does not start on Ubuntu 18.04 and gives no error

### ISSUE THREAD

**Issue by Caspercode444** [BoostIO/Boostnote#2607]
# Current behavior

V0.11.10_amd64.deb does not start on Ubuntu 18.04.1 LTS
* I tried running Boostnote and it shows  Boostnote icon in top bar with a spinner and quits after 4-5 seconds. The application does not open.
* Also, It does not run from the terminal and the cursor simply blinks forever without giving any error.
![boostnotes](https://user-images.githubusercontent.com/45028805/48510207-20673680-e821-11e8-9e6f-77bc3a146924.gif)
* I read #2555 which seems similar but I didn't get any segmentation fault error.
* I uninstalled v0.11.10 and installed v0.11.6 but it has same problem on my computer.
* Also tried v0.11.11-pre but it does not start and quits similarly.
Any guidance on how to spot the exact problem?
# Expected behaviour
It should start.

# Steps to reproduce

1. Install Boostnote 0.11.10 on Ubuntu 18.04
2. It does not run after installation

# Environment

- Version : 0.11.10
- OS Version and name : Ubuntu 18.04.1 LTS

**Comment by tscangussu** [comment]
Boostnote 0.11.10 doesn't work on Ubuntu 18.10 either but 0.11.11 works.

**Comment by ZeroX-DG** [comment]
Can you clone the repo and start it with `npm run dev` ?

**Comment by Caspercode444** [comment]
Here is the error log 
```
> boost@0.11.11 dev /home/dample/Development/boostnote/Boostnote
> node dev-scripts/dev.js

/home/dample/Development/boostnote/Boostnote/webpack-skeleton.js:24
  plugins: [new webpack.NoErrorsPlugin(), new NodeTargetPlugin()],
            ^

TypeError: webpack.NoErrorsPlugin is not a constructor
    at Object.<anonymous> (/home/dample/Development/boostnote/Boostnote/webpack-skeleton.js:24:13)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/dample/Development/boostnote/Boostnote/webpack.config.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! boost@0.11.11 dev: `node dev-scripts/dev.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the boost@0.11.11 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```
Complete log file from /.npm/_logs/
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.4.1
3 info using node@v11.2.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle boost@0.11.11~predev: boost@0.11.11
6 info lifecycle boost@0.11.11~dev: boost@0.11.11
7 verbose lifecycle boost@0.11.11~dev: unsafe-perm in lifecycle true
8 verbose lifecycle boost@0.11.11~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/dample/Development/boostnote/Boostnote/node_modules/.bin:/home/dample/gems/bin:/home/dample/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-10-oracle/bin:/usr/lib/jvm/java-10-oracle/db/bin:/usr/lib/jvm/java-9-openjdk-amd64/bin
9 verbose lifecycle boost@0.11.11~dev: CWD: /home/dample/Development/boostnote/Boostnote
10 silly lifecycle boost@0.11.11~dev: Args: [ '-c', 'node dev-scripts/dev.js' ]
11 silly lifecycle boost@0.11.11~dev: Returned: code: 1  signal: null
12 info lifecycle boost@0.11.11~dev: Failed to exec dev script
13 verbose stack Error: boost@0.11.11 dev: `node dev-scripts/dev.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid boost@0.11.11
15 verbose cwd /home/dample/Development/boostnote/Boostnote
16 verbose Linux 4.15.0-39-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v11.2.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error boost@0.11.11 dev: `node dev-scripts/dev.js`
22 error Exit status 1
23 error Failed at the boost@0.11.11 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by lukaswerner** [comment]
No updates on this? Cannot use boostnote :(

**Comment by ZeroX-DG** [comment]
@caspercode444 it’s the error you show doesn’t related to the current bug. May try delete node_mudule and run yarn to reinstall the dependencies?

**Comment by dnegreira** [comment]
seems fixed on 0.11.12 on 18.04

**Comment by MiloTodt** [comment]
Was able to install and run boostnote_0.11.12_amd64.deb from official website without issue.

Was tested on a Virtual machine, fresh install, patched, Ubuntu 18.04.1 LTS

**Comment by psFournier** [comment]
Hello,

I have the same problem, fresh install of ubuntu 16.04, downloaded boostnote_0.11.15_amd64.deb, installed it without pb, but boostnote does not start...

**Comment by psFournier** [comment]
I fixed the problem on my side by sudo apt-get install --reinstall libnss3, but i don't know if the fix will do for 18.04

**Comment by Flexo013** [comment]
@Caspercode444 Is this still happening with 0.12.1?

**Comment by Flexo013** [comment]
I'm closing this issue do to prolonged inactivity.

If you still are experiencing this problem then feel free to reopen this issue or create a new issue with all the relevant information.
