### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by truongvan** [BoostIO/Boostnote#2967]
# Current behavior

I shows the error:

A JavaScript error occurred in the main process
Uncaught Exception:
RangeError [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 536870212
    at Object.getSystemErrorName (util.js:1278:11)
    at exceptionWithHostPort (internal/errors.js:328:21)
    at internalConnect (net.js:929:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1080:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:55:10)

if I'd like to close it then, it still run in background, so it must be closed by force quit.

Do not show the error, and quit completely.

# Steps to reproduce

1. Open it on Applications
2. Lulu Firewall ask open connection for Boostnote
3. Choosing block.
4. Close Boostnote
5. Open Boostnote
6. The error appears

# Environment

- Version : Version 0.11.15 (0.11.15)
- OS Version and name : Mac OS X 10.14.4 (Build 18E226)

**Comment by Flexo013** [comment]
While it is understandable that stuff breaks if you block Boosnote's internet connection, I do agree that we should handle this problem better with some sort of nicer error message that handles this better. For example: "Error: Boostnote could not connect to GitHub!"
