### ISSUE TITLE
Not able to create a folder on google drive

### ISSUE THREAD

**Issue by ysridivya** [BoostIO/Boostnote#3003]
# Current behavior

I am trying to save the notes to the google drive. But I am not able to create a new folder on google drive

# Expected behavior
A new folder needs to be created. 

# Steps to reproduce

1. Added the new storage location using preferences -> storage -> add storage location. 
2. The path here is the local google drive path. 
3.  Create folder using + sign on the storage location 

# Environment

- Version : 0.11.12
- OS Version and name : Ubuntu 19.04

**Comment by ZeroX-DG** [comment]
Can you toggle the dev tool and take a picture of it?

**Comment by ysridivya** [comment]
> Can you toggle the dev tool and take a picture of it?

Sorry I am new to boostnote. Could you post the steps ?

**Comment by ZeroX-DG** [comment]
Oops, sorry, forgot to do that. Here you go: https://github.com/BoostIO/Boostnote/blob/master/docs/debug.md

**Comment by ysridivya** [comment]
I do not have a MAC.
While trying to debug through visual studio I am getting the following error. 
Attribute runtimeExecutable does not exist('path/to/folder/node_modules/.bin/electron')

**Comment by ysridivya** [comment]
I am new to using the node modules. 
After doing npm install and running as mentioned in the page I am now getting the following error: 

> Failed to load resource: net::ERR_FILE_NOT_FOUND [file:///media/sridivyay/Workspace/boostnote_source/Boostnote/node_modules/codemirror-mode-elixir/dist/elixir.js]
SourceMaps.getMapForGeneratedPath: exception while processing path: /media/sridivyay/Workspace/boostnote_source/Boostnote/node_modules/@rokt33r/js-sequence-diagrams/dist/sequence-diagram-min.js, sourcemap: sequence-diagram.js
SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at new SourceMap (/home/sridivyay/.vscode/extensions/msjsdiag.debugger-for-chrome-4.11.3/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:19:25)
    at sourceMapContentsP.then.contents (/home/sridivyay/.vscode/extensions/msjsdiag.debugger-for-chrome-4.11.3/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMapFactory.js:54:28)
Failed to load resource: net::ERR_CONNECTION_REFUSED [http://localhost:8080/assets/main.js]

**Comment by ysridivya** [comment]
I mounted my google drive instead of using it as a local folder. Will that create an issue?

**Comment by okasandayo** [comment]
There's a same issue and here is the capture. I could create a new note several days ago.
<img width="720" alt="Boostnote" src="https://user-images.githubusercontent.com/38093043/57673973-cc66ce80-7658-11e9-9b95-f63b57a3d5b8.png">

Also, I found that Google Drive File Stream on Mac seems that not to work properly. The app asked me to allow control of computer and still loading after 5~6 hours.

**Comment by rockneverdies55** [comment]
I get to see this when trying to create a folder under storage that's created in gdrive mount:

```
main.js:78041 Error: ESPIPE: invalid seek, write
    at Object.fs.writeSync (fs.js:707:3)
    at Object.fs.writeFileSync (fs.js:1331:24)
    at Object.writeFileSync (/usr/lib/boostnote/resources/app/node_modules/fs-plus/lib/fs-plus.js:288:17)
    at Object.writeFileSync (/usr/lib/boostnote/resources/app/node_modules/@rokt33r/season/lib/cson.js:224:17)
    at createFolder (file:///usr/lib/boostnote/resources/app/compiled/main.js:73140:11)
```

**Comment by Flexo013** [comment]
Currently I'd recommend just having the files locally and those synced to a gdrive folder. It's not like the note files take up an enormous amount of disk space.

Boostnote does not really work with synchronization at the moment; let alone not actually having the local files because they are streamed.

**Comment by hiiwave** [comment]
Just FYI, using Google Drive File Stream as storage on Windows is mostly fine. Except that I cannot open an attachment under that storage when clicking the link (somewhat related to #2003).
