### ISSUE TITLE
Exception was thrown when two boostnote is launched

### ISSUE THREAD

**Issue by moba1** [BoostIO/Boostnote#3241]
# Current behavior
I tried to launch Boostnote as another process with Boostnote already running, then the following exception was thrown:
```
(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.
internal/modules/cjs/loader.js:604
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/usr/share/boostnote/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.get [as dialog] (/usr/share/boostnote/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/usr/share/boostnote/resources/electron.asar/browser/init.js:54:31)
    at process.emit (events.js:182:13)
    at process._fatalException (internal/bootstrap/node.js:451:27)
```

# Expected behavior
If Boostnote is started when Boostnote is already running, above exception should not be thrown.

# Steps to reproduce

1. launch Boostnote
2. launch Boostnote as another process

# Environment

- Version : 0.12.1
- OS Version and name : Arch Linux

**Comment by jhdcruz** [comment]
I know a fix for this, I'll try working on this when I have the free time to do so.

**Comment by arcturus140** [comment]
Both applications of Boostnote are using the same system directory for configurations. using two instances could lead to unpredictable behaviour. what happens if one application changes settings? or stores settings on exit? or two instances of different versions are used? 

they must work in standalone for this use case. I don't know if this has been implemented yet.

**Comment by jhdcruz** [comment]
@arcturus140 That's why **Single Instance**  is implemented. However, the electron npm package was upgraded to the point the original code for it was deprecated, and so was updated in my PR. (which should work fine... probably)
