### ISSUE TITLE
Boostnote Won't Start After Latest Update

### ISSUE THREAD

**Issue by kgwood39** [BoostIO/Boostnote#3312]
I started BoostNote and it said that there was an update that was downloading and the application exited.  I see in the boost directory that app-0.13.0 has downloaded.  I attempt to start the application and it immediately exits.  

The application should open and present my notes.  Here is the appropriate section from SquirrelSetup.log:
2019-10-24 11:33:49> Program: Starting Squirrel Updater: --checkForUpdate https://github.com/BoostIO/boost-releases/releases/download/v0.13.0
2019-10-24 11:33:49> Program: Fetching update information, downloading from https://github.com/BoostIO/boost-releases/releases/download/v0.13.0
2019-10-24 11:33:49> CheckForUpdateImpl: Using existing staging user ID: 6ba2c424-16fb-5211-bc74-b5dfdc5d7381
2019-10-24 11:33:49> CheckForUpdateImpl: Downloading RELEASES file from https://github.com/BoostIO/boost-releases/releases/download/v0.13.0
2019-10-24 11:33:49> FileDownloader: Downloading url: https://github.com/BoostIO/boost-releases/releases/download/v0.13.0/RELEASES?id=boost&localVersion=0.12.1&arch=amd64
2019-10-24 11:33:50> UpdateInfo: Couldn't get release notes for:boost-0.13.0-full.nupkg: System.IO.FileNotFoundException: Could not find file 'C:\Users\kewoo\AppData\Local\boost\packages\boost-0.13.0-full.nupkg'.
File name: 'C:\Users\kewoo\AppData\Local\boost\packages\boost-0.13.0-full.nupkg'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.ZipPackage.<>c__DisplayClass9_0.<.ctor>b__0()
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2019-10-24 12:02:52> Program: Starting Squirrel Updater: 
2019-10-24 12:04:54> Program: Starting Squirrel Updater: 

boost-0.13.0-full.nupkg is in the path specified and I've reset the folder permissions for boost to be able to write to its own directory.  I still cannot start it.

- Version : 0.13.0
- OS Version and name :  Windows 10

**Comment by kgwood39** [comment]
The application is now unusable since I can't start it.
Is there a way I can go back to the previous version or reinstall it without losing my existing notes?  Some immediate workaround would be greatly appreciated.

**Comment by arcturus140** [comment]
yes you can install the latest version yourself. it will not affect your notes

**Comment by arcturus140** [comment]
same for uninstall. you may want to uninstall Boostnote and install a previous or the latest version.

**Comment by Flexo013** [comment]
I'm closing this one for now. Feel free to reopen this issue if you are still experiencing it.
