### ISSUE TITLE
Not starting after update to 0.15.1

### ISSUE THREAD

**Issue by cdokolas** [BoostIO/Boostnote#3513]
# Current behavior

I opened Boostnote (was v0.15.0) and it notified me of an upgrade. After waiting for 2-3 minutes to get the restart notification and not seeing it, I decided to close and re-open the app manually. Opening it did nothing. The new version folder is there, but running the app via `Boostnote.exe` does nothing. Additionally, there is a warning in the "System" event log (for every launch attempt):

```
The machine-default permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{C2F03A33-21F5-47FA-B4BB-156362A2F239}
 and APPID 
{316CDED5-E4AE-4B15-9113-7055D84DCC97}
 to the user [REDACTED]\[REDACTED] SID (S-1-5-21-[REDACTED]) from address LocalHost (Using LRPC) running in the application container Microsoft.Windows.ShellExperienceHost_10.0.18362.449_neutral_neutral_cw5n1h2txyewy SID (S-1-15-2-155514346-2573954481-755741238-1654018636-1233331829-3075935687-2861478708). This security permission can be modified using the Component Services administrative tool.
```

Squirrel update log (today only):
```
2020-02-05 17:24:10> Program: Starting Squirrel Updater: --checkForUpdate https://github.com/BoostIO/boost-releases/releases/download/v0.14.0
2020-02-05 17:24:10> Program: Fetching update information, downloading from https://github.com/BoostIO/boost-releases/releases/download/v0.14.0
2020-02-05 17:24:10> CheckForUpdateImpl: Using existing staging user ID: [REDACTED]
2020-02-05 17:24:10> CheckForUpdateImpl: Downloading RELEASES file from https://github.com/BoostIO/boost-releases/releases/download/v0.14.0
2020-02-05 17:24:10> FileDownloader: Downloading url: https://github.com/BoostIO/boost-releases/releases/download/v0.14.0/RELEASES?id=boost&localVersion=0.13.0&arch=amd64
2020-02-05 17:24:11> UpdateInfo: Couldn't get release notes for:boost-0.14.0-full.nupkg: System.IO.FileNotFoundException: Could not find file 'C:\Users\[REDACTED]\AppData\Local\boost\packages\boost-0.14.0-full.nupkg'.
File name: 'C:\Users\[REDACTED]\AppData\Local\boost\packages\boost-0.14.0-full.nupkg'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.ZipPackage.<>c__DisplayClass9_0.<.ctor>b__0()
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2020-02-05 17:24:11> Program: Starting Squirrel Updater: --update https://github.com/BoostIO/boost-releases/releases/download/v0.14.0
2020-02-05 17:24:11> Program: Starting update, downloading from https://github.com/BoostIO/boost-releases/releases/download/v0.14.0
2020-02-05 17:24:11> Program: About to update to: C:\Users\[REDACTED]\AppData\Local\boost
2020-02-05 17:24:11> CheckForUpdateImpl: Using existing staging user ID: [REDACTED]
2020-02-05 17:24:11> CheckForUpdateImpl: Downloading RELEASES file from https://github.com/BoostIO/boost-releases/releases/download/v0.14.0
2020-02-05 17:24:11> FileDownloader: Downloading url: https://github.com/BoostIO/boost-releases/releases/download/v0.14.0/RELEASES?id=boost&localVersion=0.13.0&arch=amd64
2020-02-05 17:24:12> FileDownloader: Downloading file: https://github.com/BoostIO/boost-releases/releases/download/v0.14.0/boost-0.14.0-full.nupkg
2020-02-05 17:24:24> ApplyReleasesImpl: Writing files to app directory: C:\Users\[REDACTED]\AppData\Local\boost\app-0.14.0
2020-02-05 17:24:27> LogHost: Rigging execution stub for Boostnote_ExecutionStub.exe to C:\Users\[REDACTED]\AppData\Local\boost\Boostnote.exe
2020-02-05 17:26:33> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\[REDACTED]\AppData\Local\boost\app-0.14.0\Boostnote.exe]
2020-02-05 17:26:33> ApplyReleasesImpl: Starting fixPinnedExecutables
2020-02-05 17:26:33> ApplyReleasesImpl: Examining Pin: Apache NetBeans IDE 11.2.lnk
2020-02-05 17:26:33> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2020-02-05 17:26:33> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2020-02-05 17:26:33> ApplyReleasesImpl: Examining Pin: Mozilla Firefox.lnk
2020-02-05 17:26:33> ApplyReleasesImpl: Fixing up tray icons
2020-02-05 17:26:33> ApplyReleasesImpl: cleanDeadVersions: for version 0.14.0
2020-02-05 17:26:33> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.13.0
2020-02-05 17:26:33> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.14.0
2020-02-05 17:26:42> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: Could not find a part of the path 'C:\Users\fluke\Code\Boostnote\resources\app.ico'. ---> System.Net.WebException: Could not find a part of the path 'C:\Users\fluke\Code\Boostnote\resources\app.ico'. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\fluke\Code\Boostnote\resources\app.ico'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   --- End of inner exception stack trace ---
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   at System.Net.FileWebRequest.GetResponseCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()
2020-02-05 17:28:19> Program: Starting Squirrel Updater: --processStartAndWait Boostnote.exe
2020-02-05 17:28:19> Program: Want to launch 'C:\Users\[REDACTED]\AppData\Local\boost\app-0.14.0\Boostnote.exe'
2020-02-05 17:28:19> Program: About to wait for parent PID 23276
2020-02-05 17:28:19> Program: About to launch: 'C:\Users\[REDACTED]\AppData\Local\boost\app-0.14.0\Boostnote.exe': 
2020-02-24 13:58:04> Program: Starting Squirrel Updater: --checkForUpdate https://github.com/BoostIO/boost-releases/releases/download/v0.15.0
2020-02-24 13:58:04> Program: Fetching update information, downloading from https://github.com/BoostIO/boost-releases/releases/download/v0.15.0
2020-02-24 13:58:04> CheckForUpdateImpl: Using existing staging user ID: [REDACTED]
2020-02-24 13:58:04> CheckForUpdateImpl: Downloading RELEASES file from https://github.com/BoostIO/boost-releases/releases/download/v0.15.0
2020-02-24 13:58:04> FileDownloader: Downloading url: https://github.com/BoostIO/boost-releases/releases/download/v0.15.0/RELEASES?id=boost&localVersion=0.14.0&arch=amd64
2020-02-24 13:58:05> UpdateInfo: Couldn't get release notes for:boost-0.15.0-full.nupkg: System.IO.FileNotFoundException: Could not find file 'C:\Users\[REDACTED]\AppData\Local\boost\packages\boost-0.15.0-full.nupkg'.
File name: 'C:\Users\[REDACTED]\AppData\Local\boost\packages\boost-0.15.0-full.nupkg'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.ZipPackage.<>c__DisplayClass9_0.<.ctor>b__0()
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2020-02-24 13:58:05> Program: Starting Squirrel Updater: --update https://github.com/BoostIO/boost-releases/releases/download/v0.15.0
2020-02-24 13:58:05> Program: Starting update, downloading from https://github.com/BoostIO/boost-releases/releases/download/v0.15.0
2020-02-24 13:58:05> Program: About to update to: C:\Users\[REDACTED]\AppData\Local\boost
2020-02-24 13:58:05> CheckForUpdateImpl: Using existing staging user ID: [REDACTED]
2020-02-24 13:58:05> CheckForUpdateImpl: Downloading RELEASES file from https://github.com/BoostIO/boost-releases/releases/download/v0.15.0
2020-02-24 13:58:05> FileDownloader: Downloading url: https://github.com/BoostIO/boost-releases/releases/download/v0.15.0/RELEASES?id=boost&localVersion=0.14.0&arch=amd64
2020-02-24 13:58:06> FileDownloader: Downloading file: https://github.com/BoostIO/boost-releases/releases/download/v0.15.0/boost-0.15.0-full.nupkg
2020-02-24 13:59:35> ApplyReleasesImpl: Writing files to app directory: C:\Users\[REDACTED]\AppData\Local\boost\app-0.15.0
2020-02-24 13:59:37> LogHost: Rigging execution stub for Boostnote_ExecutionStub.exe to C:\Users\[REDACTED]\AppData\Local\boost\Boostnote.exe
2020-02-24 14:01:34> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\[REDACTED]\AppData\Local\boost\app-0.15.0\Boostnote.exe]
2020-02-24 14:01:35> ApplyReleasesImpl: Starting fixPinnedExecutables
2020-02-24 14:01:35> ApplyReleasesImpl: Examining Pin: Apache NetBeans IDE 11.2.lnk
2020-02-24 14:01:35> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2020-02-24 14:01:35> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2020-02-24 14:01:35> ApplyReleasesImpl: Examining Pin: Mozilla Firefox.lnk
2020-02-24 14:01:35> ApplyReleasesImpl: Fixing up tray icons
2020-02-24 14:01:35> ApplyReleasesImpl: cleanDeadVersions: for version 0.15.0
2020-02-24 14:01:35> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.14.0
2020-02-24 14:01:35> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.15.0
2020-02-24 14:01:42> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: Could not find a part of the path 'C:\Users\fluke\Code\Boostnote\resources\app.ico'. ---> System.Net.WebException: Could not find a part of the path 'C:\Users\fluke\Code\Boostnote\resources\app.ico'. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\fluke\Code\Boostnote\resources\app.ico'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   --- End of inner exception stack trace ---
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   at System.Net.FileWebRequest.GetResponseCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()
2020-02-24 14:01:54> Program: Starting Squirrel Updater: --processStartAndWait Boostnote.exe
2020-02-24 14:01:54> Program: Want to launch 'C:\Users\[REDACTED]\AppData\Local\boost\app-0.15.0\Boostnote.exe'
2020-02-24 14:01:54> Program: About to wait for parent PID 20840
2020-02-24 14:01:54> Program: About to launch: 'C:\Users\[REDACTED]\AppData\Local\boost\app-0.15.0\Boostnote.exe': 
2020-03-04 10:02:53> Program: Starting Squirrel Updater: --checkForUpdate https://github.com/BoostIO/boost-releases/releases/download/v0.15.1
2020-03-04 10:02:53> Program: Fetching update information, downloading from https://github.com/BoostIO/boost-releases/releases/download/v0.15.1
2020-03-04 10:02:53> CheckForUpdateImpl: Using existing staging user ID: [REDACTED]
2020-03-04 10:02:53> CheckForUpdateImpl: Downloading RELEASES file from https://github.com/BoostIO/boost-releases/releases/download/v0.15.1
2020-03-04 10:02:53> FileDownloader: Downloading url: https://github.com/BoostIO/boost-releases/releases/download/v0.15.1/RELEASES?id=boost&localVersion=0.15.0&arch=amd64
2020-03-04 10:02:54> UpdateInfo: Couldn't get release notes for:boost-0.15.1-full.nupkg: System.IO.FileNotFoundException: Could not find file 'C:\Users\[REDACTED]\AppData\Local\boost\packages\boost-0.15.1-full.nupkg'.
File name: 'C:\Users\[REDACTED]\AppData\Local\boost\packages\boost-0.15.1-full.nupkg'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.ZipPackage.<>c__DisplayClass9_0.<.ctor>b__0()
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2020-03-04 10:26:20> Program: Starting Squirrel Updater: 
2020-03-04 10:30:53> Program: Starting Squirrel Updater: 
```
Launching the updater now (twice) produced the last two lines!

# Expected behavior

Should open with the new version (0.15.1)

# Steps to reproduce

Unknown if reproducible
1. Open 0.15.1
1. Restart the app after

# Environment

- Boostnote version: 0.15.1
- OS version and name: Windows 10 (64-bit)

**Comment by Flexo013** [comment]
Did you download the installer exe for 0.15.1 or use the auto updater?

(I had no problems using the installer on Windows 10 (64-bit)

**Comment by cdokolas** [comment]
Thanks for responding. I thought I'd made it clear: it was the auto-updater.

I'm now keeping the installation in a broken state just for debugging purposes. Let me know if you want anything more, or if I can use the installer to fix it.

**Comment by caloveri** [comment]
I have the same problem having used the auto-updater

`2020-02-24 16:04:45> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: Could not find a part of the path 'C:\Users\fluke\Code\Boostnote\resources\app.ico'. ---> System.Net.WebException: Could not find a part of the path 'C:\Users\fluke\Code\Boostnote\resources\app.ico'. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\fluke\Code\Boostnote\resources\app.ico'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   --- End of inner exception stack trace ---
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   at System.Net.FileWebRequest.GetResponseCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()`

and

`2020-02-24 16:05:22> Program: Starting Squirrel Updater: --processStartAndWait Boostnote.exe
2020-02-24 16:05:22> Program: Want to launch 'C:\Users\erikp\AppData\Local\boost\app-0.15.0\Boostnote.exe'
2020-02-24 16:05:22> Program: About to wait for parent PID 34752
2020-02-24 16:05:22> Program: About to launch: 'C:\Users\erikp\AppData\Local\boost\app-0.15.0\Boostnote.exe': 
2020-03-04 17:56:44> Program: Starting Squirrel Updater: --checkForUpdate https://github.com/BoostIO/boost-releases/releases/download/v0.15.1
2020-03-04 17:56:44> Program: Fetching update information, downloading from https://github.com/BoostIO/boost-releases/releases/download/v0.15.1
2020-03-04 17:56:44> CheckForUpdateImpl: Using existing staging user ID: b7cf06d7-3285-51be-9942-1e644418ac0b
2020-03-04 17:56:44> CheckForUpdateImpl: Downloading RELEASES file from https://github.com/BoostIO/boost-releases/releases/download/v0.15.1
2020-03-04 17:56:44> FileDownloader: Downloading url: https://github.com/BoostIO/boost-releases/releases/download/v0.15.1/RELEASES?id=boost&localVersion=0.15.0&arch=amd64
2020-03-04 17:56:44> UpdateInfo: Couldn't get release notes for:boost-0.15.1-full.nupkg: System.IO.FileNotFoundException: Could not find file 'C:\Users\erikp\AppData\Local\boost\packages\boost-0.15.1-full.nupkg'.
File name: 'C:\Users\erikp\AppData\Local\boost\packages\boost-0.15.1-full.nupkg'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.ZipPackage.<>c__DisplayClass9_0.<.ctor>b__0()
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)`

**Comment by Flexo013** [comment]
@cdokolas @caloveri Please attempt a manual installation of the update. This is enough info for us.
