### ISSUE TITLE
HMR server gives error

### ISSUE THREAD

**Issue by metinn** [BoostIO/Boostnote#50]
Hi, 
When i run ``npm run webpack`` i get the error below. What is this ?

```
ERROR in ./~/css-loader!./~/stylus-loader!./browser/styles/main/index.styl
Module build failed: TypeError: /Users/metinguler/Desktop/electron/Boostnote/browser/styles/main/index.styl:159:1
   155|     opacity 0.7
   156|     &:hover
   157|       opacity 1
   158|       background-color lighten(brandColor, 10%)
   159| 
--------^

Path must be a string. Received undefined

    at assertPath (path.js:7:11)
    at extname (path.js:1433:5)
    at new SourceMapper (/Users/metinguler/Desktop/electron/Boostnote/node_modules/stylus/lib/visitor/sourcemapper.js:41:7)
    at Renderer.render (/Users/metinguler/Desktop/electron/Boostnote/node_modules/stylus/lib/renderer.js:94:9)
    at /Users/metinguler/Desktop/electron/Boostnote/node_modules/stylus-loader/index.js:149:12
    at tryCatchReject (/Users/metinguler/Desktop/electron/Boostnote/node_modules/when/lib/makePromise.js:840:30)
    at runContinuation1 (/Users/metinguler/Desktop/electron/Boostnote/node_modules/when/lib/makePromise.js:799:4)
    at Fulfilled.when (/Users/metinguler/Desktop/electron/Boostnote/node_modules/when/lib/makePromise.js:590:4)
    at Pending.run (/Users/metinguler/Desktop/electron/Boostnote/node_modules/when/lib/makePromise.js:481:13)
    at Scheduler._drain (/Users/metinguler/Desktop/electron/Boostnote/node_modules/when/lib/Scheduler.js:62:19)
 @ ./browser/styles/main/index.styl 4:14-130 13:2-17:4 14:20-136
```

**Comment by Rokt33r** [comment]
Did you modify some code? If you did, please tell me where you did it.

**Comment by metinn** [comment]
No i did'nt modify any code

**Comment by Rokt33r** [comment]
It seems to be the problem of stylus loader. 
I also confronted exactly same problem when I use the stable version of node last weekend. Try LTS version like v4.4.4.

If this comment doesn't work, feel free to re-open this issue.

**Comment by yosmoc** [comment]
Hi,

I also fallen into this error. I know this is not the Boostnote bug, but this issue will help someone like us. I suggest to put this information in https://github.com/BoostIO/Boostnote/blob/master/docs/build.md .

**Comment by Rokt33r** [comment]
@yosmoc Thanks for your suggesting. I'll update the document.
