### ISSUE TITLE
ERROR in ./~/css-loader!./~/stylus-loader?sourceMap!./browser/main/global.styl

### ISSUE THREAD

**Issue by eschmid72** [BoostIO/Boostnote#79]
Actually, I can't run webpack, I'm getting 22 error messages like this:

```
ERROR in ./~/css-loader!./~/stylus-loader?sourceMap!./browser/main/global.styl
Module build failed: TypeError: /home/egon/electron/Boostnote/browser/main/global.styl:86:1
   82|   .modalBack
   83|     absolute top left bottom right
   84|     background-color modalBackColor
   85|     z-index modalZIndex + 1
   86| 
-------^

Path must be a string. Received undefined

    at assertPath (path.js:7:11)
    at extname (path.js:1433:5)
    at new SourceMapper (/home/egon/electron/Boostnote/node_modules/stylus/lib/visitor/sourcemapper.js:41:7)
    at Renderer.render (/home/egon/electron/Boostnote/node_modules/stylus/lib/renderer.js:94:9)
    at /home/egon/electron/Boostnote/node_modules/stylus-loader/index.js:149:12
    at tryCatchReject (/home/egon/electron/Boostnote/node_modules/when/lib/makePromise.js:840:30)
    at runContinuation1 (/home/egon/electron/Boostnote/node_modules/when/lib/makePromise.js:799:4)
    at Fulfilled.when (/home/egon/electron/Boostnote/node_modules/when/lib/makePromise.js:590:4)
    at Pending.run (/home/egon/electron/Boostnote/node_modules/when/lib/makePromise.js:481:13)
    at Scheduler._drain (/home/egon/electron/Boostnote/node_modules/when/lib/Scheduler.js:62:19)
 @ ./~/style-loader!./~/css-loader!./~/stylus-loader?sourceMap!./browser/main/global.styl 4:14-135 13:2-17:4 14:20-141
```

**Comment by Rokt33r** [comment]
Which version of node you are using?

**Comment by eschmid72** [comment]
I've been using 6.x, well, there it failed, but with 5.1.1 it seems to work.

But only if I start with `npm run hot`...

When I build with `webpack` and start with `npm start`, I am getting this error:

```
main.html:51 Uncaught Error: locals[0] does not appear to be a `module` object with
Hot Module replacement API enabled. You should disable react-transform-hmr in production
by using `env` section in Babel configuration. See the example in README:
https://github.com/gaearon/react-transform-hmr
```

**Comment by Rokt33r** [comment]
`npm start` is for only production env.  You should have compiled codes to run it.
And, the compiled code will be generated by `grunt compile`.

So, try `grunt compile` before running `npm start`.

**FYI**:  `npm run webpack` is to run HMR server for development. It won't generate any code .
**p.s.** I'll update `readme.md` about this issue on this weekend.
